# Generated by Django 5.2.3 on 2025-06-19 19:41
# pylint: skip-file

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.role'),
        ),
    ]
