# Generated by Django 5.2.3 on 2025-06-24 11:58
# pylint: skip-file

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.role'),
        ),
    ]
