# Generated by Django 5.2.3 on 2025-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photo_public_id_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_type',
            field=models.CharField(choices=[('trail', 'Trilha'), ('water_fall', 'Cachoeira'), ('park', 'Parque'), ('farm', 'Fazenda'), ('other', 'Outro')]),
        ),
    ]
