# Generated by Django 5.2.3 on 2025-07-02 18:43
# pylint: skip-file

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_point_views_alter_point_point_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='avg_rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
