# Generated by Django 5.2.3 on 2025-07-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_point_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
