# Generated by Django 5.2.3 on 2025-07-03 11:23
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_point_status_alter_point_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
