# Generated by Django 5.2.3 on 2025-07-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_emailverification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
