name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: .env
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host:      ${{ secrets.SSH_HOST_PROD }}
          username:  root
          key:       ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd ~/back/

            git pull origin main

            docker compose build
            docker compose up -d --remove-orphans